### ISSUE TITLE
Latest upgrade = self-hosting issues

### ISSUE THREAD

**Issue by plague-doctor** [miroslavpejic85/mirotalk#271]
### Describe the bug

Latest upgrade of  mirotalk/p2p prevents me from using the service... 
The service hangs on "Loading..."

My swarm configuration:

```
version: '3'

services:
  mirotalk:
    image: mirotalk/p2p:latest
    networks:
      - proxy
    environment:
      HTTPS: 'false'
      HOST: talk.netsi.xyz
      PORT: 3000
      TZ: 'Australia/Melbourne'
      LOGS_DEBUG: 'true'
      CORS_ORIGIN: '*'
      CORS_METHODS: '["GET", "POST"]'
      HOST_PROTECTED: 'true'
      HOST_USER_AUTH: 'false'
      HOST_USERS: '[{"username": "${username1}", "password": "$password1"},{"username": "${username2}", "password": "$password2"}]'
      PRESENTERS: '["U1","U2"]'
      JWT_KEY: ${JWT_KEY}
      JWT_EXP: 1h
      NGROK_ENABLED: 'false'
      STUN_SERVER_ENABLED: 'true'
      STUN_SERVER_URL: stun:coturn.xxx.xyz:5349
      TURN_SERVER_ENABLED: 'true'
      TURN_SERVER_URL: turn:coturn.xxx.xyz:5349
      TURN_SERVER_USERNAME: ${TURN_SERVER_USERNAME}
      TURN_SERVER_CREDENTIAL: ${TURN_SERVER_CREDENTIAL}
      IP_LOOKUP_ENABLED: 'false'
      API_KEY_SECRET: ${API_KEY_SECRET}
      SURVEY_ENABLED: 'false'
      REDIRECT_ENABLED: 'false'
      SENTRY_ENABLED: 'false'
      SLACK_ENABLED: 'false'
      MATTERMOST_ENABLED: 'false'
      CHATGPT_ENABLED: 'false'
      MAIL_ALERT: 'false'
      STATS_ENABLED: 'false'
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mirotalk.rule=Host(`talk.xxx.xyz`)"
        - "traefik.http.routers.mirotalk.tls.certresolver=letsencrypt"
        - "traefik.http.routers.mirotalk.entrypoints=https"
        - "traefik.http.routers.mirotalk.tls=true"
        - "traefik.http.services.mirotalk.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true

```

### Steps to reproduce

start the container and try to connect 

### Expected behavior

service asks to get access to the camera and microphone, and let users to the room.

### Device

- [ ] Android
- [ ] iPhone
- [X] Linux
- [ ] Mac
- [ ] Windows

### Browser

- [X] Chrome (or Chromium based)
- [X] Firefox
- [ ] Safari
- [ ] Android browser
- [ ] iOS browser
- [X] Other desktop browser

### Relevant log output

```shell
> mirotalk@1.4.34 start
> node app/src/server.js
Logs { colors: true, debug: true }
[1/7/2025, 09:26:36:966] [server] Module not found './config'
[1/7/2025, 09:26:37:440] [server] 
	███████╗██╗ ██████╗ ███╗   ██╗      ███████╗███████╗██████╗ ██╗   ██╗███████╗██████╗ 
	██╔════╝██║██╔════╝ ████╗  ██║      ██╔════╝██╔════╝██╔══██╗██║   ██║██╔════╝██╔══██╗
	███████╗██║██║  ███╗██╔██╗ ██║█████╗███████╗█████╗  ██████╔╝██║   ██║█████╗  ██████╔╝
	╚════██║██║██║   ██║██║╚██╗██║╚════╝╚════██║██╔══╝  ██╔══██╗╚██╗ ██╔╝██╔══╝  ██╔══██╗
	███████║██║╚██████╔╝██║ ╚████║      ███████║███████╗██║  ██║ ╚████╔╝ ███████╗██║  ██║
	╚══════╝╚═╝ ╚═════╝ ╚═╝  ╚═══╝      ╚══════╝╚══════╝╚═╝  ╚═╝  ╚═══╝  ╚══════╝╚═╝  ╚═╝ started...
	 +502ms
[1/7/2025, 09:26:37:441] [server] Server config {
  server: 'http://talk.xxx.xyz:3000',
  server_tunnel: false,
  api_docs: 'http://talk.xxx.xyz:3000/api/v1/docs',
  jwtCfg: { JWT_KEY: 'RJSMexxxxxxxxxxxxxxxxxxxxxxxsw5c', JWT_EXP: '1h' },
  cors: { origin: '*', methods: [ 'GET', 'POST' ] },
  iceServers: [
    { urls: 'stun:coturn.xxx.xyz:5349' },
    {
      urls: 'turn:coturn.xxx.xyz:5349',
      username: 'turntalk',
      credential: 'yUmTxxxxxxxxxxKaVjk'
    }
  ],
  test_ice_servers: 'http://talk.xxx.xyz:3000/icetest',
  email: false,
  oidc: false,
  host_protected: {
    protected: true,
    user_auth: false,
    users: [
      {
        username: 'user1',
        password: 'ZxxxN'
      },
      {
        username: 'user2',
        password: '2xxxO'
      }
    ],
    authenticated: false
  },
  presenters: [ 'U1', 'U2' ],
  ip_whitelist: false,
  self_signed_certificate: false,
  api_key_secret: 'Izyyxxxxxxxxxxxp1rf',
  turn_enabled: true,
  ip_lookup_enabled: false,
  chatGPT_enabled: false,
  slack_enabled: false,
  mattermost_enabled: false,
  sentry_enabled: false,
  stats: false,
  ngrok: false,
  survey: false,
  redirect: false,
  app_version: '1.4.34',
  node_version: '20.18.1'
}
[1/7/2025, 09:13:08:268] [server] New request: { ip: '172.16.30.3', method: 'GET', path: '/', body: {} } +1m
[1/7/2025, 09:13:08:273] [server] Allowed IPs { ip: '172.16.30.3', authorizedIP: false, authorizedIPs: {} }
[1/7/2025, 09:13:08:298] [server] New request: { ip: '172.16.30.3', method: 'GET', path: '/login', body: {} } +29ms
[1/7/2025, 09:13:08:368] [server] New request: { ip: '172.16.30.3', method: 'GET', path: '/stats', body: {} } +68ms
[1/7/2025, 09:13:08:377] [server] New request: { ip: '172.16.30.3', method: 'GET', path: '/brand', body: {} } +8ms
[1/7/2025, 09:13:12:200] [server] New request: { ip: '172.16.30.3', method: 'GET', path: '/login', body: {} } +3s
[1/7/2025, 09:13:12:242] [server] New request: { ip: '172.16.30.3', method: 'GET', path: '/brand', body: {} } +42ms
[1/7/2025, 09:13:15:655] [server] New request: {
  ip: '172.16.30.3',
  method: 'POST',
  path: '/login',
  body: { username: 'user1', password: 'ZxxxN' }
} +3s
[1/7/2025, 09:13:15:657] [server] Request login to host from: 172.16.30.3 { username: 'user1', password: 'ZxxxN' } +1ms
[1/7/2025, 09:13:15:660] [xss] XSS Object sanitization done '' +1m
[1/7/2025, 09:13:15:661] [server] HOST LOGIN OK {
  ip: '172.16.30.3',
  authorized: true,
  authorizedIps: { '172.16.30.3': true }
} +4ms
[1/7/2025, 09:13:15:703] [server] New request: { ip: '172.16.30.3', method: 'GET', path: '/logged', body: {} } +40ms
[1/7/2025, 09:13:15:704] [server] Allowed IPs {
  ip: '172.16.30.3',
  authorizedIP: true,
  authorizedIPs: { '172.16.30.3': true }
}
[1/7/2025, 09:13:15:711] [server] New request: { ip: '172.16.30.3', method: 'GET', path: '/', body: {} } +7ms
[1/7/2025, 09:13:15:713] [server] Allowed IPs {
  ip: '172.16.30.3',
  authorizedIP: true,
  authorizedIPs: { '172.16.30.3': true }
}
[1/7/2025, 09:13:15:801] [server] New request: { ip: '172.16.30.3', method: 'GET', path: '/brand', body: {} } +90ms
[1/7/2025, 09:13:20:531] [server] New request: {
  ip: '172.16.30.3',
  method: 'GET',
  path: '/join/04388HugeWolf',
  body: {}
} +4s
[1/7/2025, 09:13:20:535] [server] /join/:roomId {
  OIDCUserAuthenticated: false,
  hostUserAuthenticated: true,
  roomExist: false,
  roomCount: 0,
  extraInfo: {
    roomId: '04388HugeWolf',
    OIDCUserEnabled: false,
    hostProtected: true,
    hostAuthenticated: true
  },
  allowRoomAccess: true
} +1ms
[1/7/2025, 09:13:20:686] [server] New request: { ip: '172.16.30.3', method: 'GET', path: '/brand', body: {} } +149ms
```
```


### Reproducibility

No

### Additional context

_No response_
